language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t Warchitect/docker-react Dockerfile.dev .

script:
  - docker run -e CI=true Warchitect/docker-react npm run test